import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "../../lib/redux/provider";
// import NavbarComponent from "../../components/Navbars/NavbarComponent";
import NavbarHomePage from "../../components/Navbars/NavbarHomePage";
import Footer from "../../components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pierre.V Photographie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <Providers>
          <NavbarHomePage />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
